### ISSUE TITLE
`viz.structure_ft()` gone

### ISSUE THREAD

**Issue by alexsong19** [fancompute/legume#32]
This method is available in Nov 2019, but is gone in Feb commits. Didn't find any documentation on it.
What's the updated way to plot this?

**Comment by ianwilliamson** [comment]
https://legume.readthedocs.io/en/latest/generated/legume.viz.eps_ft.html#legume.viz.eps_ft

**Comment by momchilmm** [comment]
Just a note, there have been a few small changes since November, but I do keep the [API manual](https://legume.readthedocs.io/en/latest/api.html#visualization) and the [examples](https://legume.readthedocs.io/en/latest/examples.html) up to date.
