### ISSUE TITLE
What's the meaning of 'phc.layers[-1].add_shape(legume.Circle(eps=1.0, r=r))'?

### ISSUE THREAD

**Issue by Vimim3** [fancompute/legume#37]
In the example of 'Bands of a photonic crystal slab', there is a command **'phc.layers[-1].add_shape(legume.Circle(eps=1.0, r=r))'**,
Could you please explain the meaning of **'layers[-1]'** in the command? Thank you very much!

**Comment by StephenJamesCashen** [comment]
The phc.layers variable is a list of layers of the photonic crystal object, not including the upper and lower claddings. Here a circle is added to the "-1th" entry of that list. In python a negative index counts backwards from the end of the list or sequence. So -1 indexes the final entry of the list.

See https://realpython.com/lessons/indexing-and-slicing/ for more details on slicing and indexing sequences in python.

**Comment by momchilmm** [comment]
Thanks @StephenJamesCashen
