### ISSUE TITLE
MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.   linewidth=markeredgewidth)

### ISSUE THREAD

**Issue by LLJUCAS** [fancompute/legume#42]
MatplotlibDeprecationWarning: Passing parameters norm and vmin/vmax simultaneously is deprecated since 3.3 and will become an error two minor releases later. Please pass vmin/vmax directly to the norm when creating it.
  linewidth=markeredgewidth)

How to solve it?

**Comment by momchilmm** [comment]
Fixed in ed6be40a85756f27c9d87dd9306360ba6928bcc0 and deployed as version 0.1.8.
