### ISSUE TITLE
install, "requirements.txt" seems to be missing

### ISSUE THREAD

**Issue by langbenjf** [fancompute/legume#43]
Hello,

When I was installing Legume my "pip" attempts failed as it was unable to find the "requirements.txt" file. When I download the .tar.gz version of the project from github this file is also missing from that. Adding this file in manually solved all the problems and it has now installed fine. Perhaps this file is somehow missing from the tar.gz version of the project.

Thanks for the great tool, now its installed looking forward to using it.

**Comment by momchil-flex** [comment]
Thanks for pointing this out! Just pushed 0.1.9 should be fixed.
