### ISSUE TITLE
Issue defining a figure and gridspec with eps_ft in vis.py

### ISSUE THREAD

**Issue by Alex-Meek** [fancompute/legume#44]
Hello, 

I'm trying to set a figure and gridspec using the function eps_ft, upon which I get the error "NameError: name 'ars' is not defined" from within the function. 

gs = mpl.gridspec.GridSpecFromSubplotSpec(len(ars), 1, gridspec)
NameError: name 'ars' is not defined

Looking at the eps_ft function itself, it seems 'ar' is defined at line 680 but never 'ars'.

Thanks.

**Comment by momchil-flex** [comment]
Should be fixed in newly released 0.1.10
