### ISSUE TITLE
mode index of the quai-TE/TM modes of photonic crystal slabs

### ISSUE THREAD

**Issue by Vimim3** [fancompute/legume#45]
In the section ”How do I incorporate symmetry?“, the author gives the mode index of the quai-TE/TM modes of photonic crystal slabs.  Which plane is the reference plane for this classification?

**Comment by momchil-flex** [comment]
The plane for quasi-TE/quasi-TM specification is the xy plane bisecting the slab. However as noted there this is not exact classification as generally the modes are mixed. Low-frequency modes however are usually predominantly TE or prerdominantly TM w.r.t. that plane.

**Comment by Vimim3** [comment]
> The plane for quasi-TE/quasi-TM specification is the xy plane bisecting the slab. However as noted there this is not exact classification as generally the modes are mixed. Low-frequency modes however are usually predominantly TE or prerdominantly TM w.r.t. that plane.

Thank you! I note  the mode index of the quai-TE/TM modes of photonic crystal slabs is different to that of the homogeneous slab, how to determine the mode index of quasi-TE/TM mode?

**Comment by momchil-flex** [comment]
Yeah, for the slab, the TE/TM classification can be defined w.r.t. the kz plane, and the modes alternate between (true) TE and TM in that definition. For a PhC, the quasi-TE/quasi-TM classification is w.r.t. the xy plane bisecting the slab (e.g. z=0), and is more correctly a sigma_xy = -1/+1 classification, where sigma_xy is the reflection operator at that xy plane. For example a mode with sigma_xy = -1 has strictly 0 in-plane E-field but *only on that plane*. The in-plane E field can and will be nonzero at other z-s. The sigma -1/+1 values alternate as described in the FAQ on the docs, -1 modes are [0, 3, 4, 7, 8, ...] and +1 modes are [1, 2, 5, 6, ...].
