### ISSUE TITLE
Bands of a 1D photonic crystal slab

### ISSUE THREAD

**Issue by ZhimingShi** [fancompute/legume#57]
Hello, I am having problems reproducing the results in Molding the Flow of Light using this code, I don't know how to set the lattice for this structure. According to the current parameters, the results are quite different from the book. How can I reproduce the results correctly?
Here I have uploaded the simulation code（[simulation code.zip](https://github.com/fancompute/legume/files/13725873/simulation.code.zip))
![image](https://github.com/fancompute/legume/assets/121110294/8a086862-2acf-4e7f-be14-01d6560d2a67)
(Chapter07, page128)
![image](https://github.com/fancompute/legume/assets/121110294/0ac8c158-b6de-4035-af6b-44a4ffec1601)
（simulation result）

**Comment by momchil-flex** [comment]
Unfortunately legume is not well fit for nanobeam PhCs, only for 2D slabs, and it is not easy to extend the code towards that application.
