### ISSUE TITLE
questions about the dielectric constant setup

### ISSUE THREAD

**Issue by HenryTang0127** [fancompute/legume#61]
I noticed that the data type of your model is float, in some special cases, dielectric constant is complex, which means there is some loss in the material (such as metal).
So, are there methods to apply the imaginary part dielectric constant into Legume model? Is it possible to calculate a PhC slab with loss?
Thank you!

**Comment by momchilmm** [comment]
Unfortunately no, legume currently only accepts real permittivity. There are various complications with lossy modes, specifically with properly ortho normalizing the basis set.

I think what you may have seen as complex is the Fourier transform of the permittivity. For a real valued field this is still complex, but has the property that e(G) = e(-G)*

**Comment by HenryTang0127** [comment]
Thank you for your reply! 
What I want to do is to calculate the band stucture of  a PhC slab with loss, which means the permittivity has imagniary part. I will find other ways to do ti.Thank you again.
