### ISSUE TITLE
:question: Question: Periodicity in inverse design example

### ISSUE THREAD

**Issue by jan-david-fischbach** [fancompute/legume#64]
Hi @momchilmm,

do I understand it correctly that the PhC cavities in the 2020 ACS photonics paper are considered as supercells on a rectangular lattice (the size of which is determined by the desired degrees of freedom)? So, if my understanding is correct, you use the supercell approximation e.g. mentioned on page 257 of "Molding the flow of light". Do you make sure that the approximation stays valid during the optimization? This seems particularly troublesome, when optimizing only for Q, which might be achieved by a more and more delocalized mode (see page 149 of "Molding the flow of light"). 
This is probably not the right place for this question. If helpful I can move it somewhere else :)

Regards
JD

**Comment by jan-david-fischbach** [comment]
Hey, thanks a lot for clearing this up :)

**Comment by momchil-flex** [comment]
As one extra comment, generally GME tends to *over*-estimate the Q, which is I believe less common, e.g. in FDTD it's the opposite, for high Q cavities you need to work hard to get the high value out (e.g. make sure that the grid is commensurate with the PhC periodicity, that you have enough PhC periods between your cavity and PML, etc.) But yeah when GME is not well coverged even if the mode looks right it tends to produce values that are super high, and go *down* as you e.g. add more plane waves or mode indexes.
